title: Ammr Ayman - Data Analyst
description: Transforming data into actionable insights.
url: https://yourusername.github.io # Your GitHub Pages URL
theme: minima # Replace 'minima' with your chosen theme

# Your Details
name: Ammr Ayman
email: ammarayman426@gmail.com # Optional
linkedin_username: ammar-ayman-528086316
github_username: Ammarz8

# Logo Configuration 
logo: /image.jpg # Make sure 'image.img' is in the root of your repo
